### ISSUE TITLE
components wrapped in observer not (re-)rendering correctly

### ISSUE THREAD

**Issue by MCW77** [LegendApp/legend-state#259]
After upgrading to 2.1.9 from 2.1.8 i get the
  Error: Property 'displayName' does not exist on type ...

Probably introduced with
types: improve type of observer so it just passes though
https://github.com/LegendApp/legend-state/commit/656a9a94aaeb6d681ae12822ae77a241aeb6bccd

Ex: 
```
const MyComp = observer(...);
MyComp.displayName = "MyComp";
```

I can currently work around the error by adding FC type to the component.
```
const MyComp: FC<MyCompProps> = observer(...);
MyComp.displayName = "MyComp";
```

**Comment by MCW77** [comment]
Actually i just noticed, that the components wrapped in observer wouldn't render at all if not adding explicit typing

**Comment by MCW77** [comment]
And if adding the type the component renders but the observer doesn't trigger re-renders

**Comment by jmeistrich** [comment]
Thanks @MCW77. We found a better way to solve that in our app code so I reverted that change in version 2.1.10.
